export interface DisposalCategory {
  id: string;
  name: string;
  nameJa: string;
  color: string;
  description: string;
  descriptionJa: string;
  collectionNote: string;
  collectionNoteJa: string;
}

export interface ItemRule {
  itemName: string;
  itemNameJa: string;
  categoryId: string;
  synonyms: string[];
  synonymsJa: string[];
  preparationSteps: string[];
  preparationStepsJa: string[];
  specialNotes: string[];
  specialNotesJa: string[];
  tags: string[];
}

export interface MunicipalityProfile {
  id: string;
  name: string;
  nameJa: string;
  prefecture: string;
  prefectureJa: string;
  categories: DisposalCategory[];
  collectionDays: Record<string, string>;
  website: string;
  hotline: string;
  fallbackGuidance: string;
  fallbackGuidanceJa: string;
  items: ItemRule[];
}

const COMMON_CATEGORIES: Record<string, DisposalCategory> = {
  burnable: {
    id: "burnable",
    name: "Burnable Waste",
    nameJa: "燃えるゴミ",
    color: "#ef4444",
    description: "Items that can be incinerated",
    descriptionJa: "焼却できるゴミ",
    collectionNote: "Use designated red bags",
    collectionNoteJa: "指定の赤い袋を使用",
  },
  nonBurnable: {
    id: "nonBurnable",
    name: "Non-Burnable Waste",
    nameJa: "燃えないゴミ",
    color: "#6b7280",
    description: "Items that cannot be incinerated",
    descriptionJa: "焼却できないゴミ",
    collectionNote: "Use designated blue bags",
    collectionNoteJa: "指定の青い袋を使用",
  },
  plastic: {
    id: "plastic",
    name: "Plastic Packaging",
    nameJa: "プラスチックゴミ",
    color: "#8b5cf6",
    description: "Plastic containers, bags, and packaging marked with プラ",
    descriptionJa: "プラマークのついた容器・包装",
    collectionNote: "Rinse clean before disposal",
    collectionNoteJa: "軽く洗ってから出してください",
  },
  petBottle: {
    id: "petBottle",
    name: "PET Bottles",
    nameJa: "ペットボトル",
    color: "#06b6d4",
    description: "PET (polyethylene terephthalate) beverage bottles",
    descriptionJa: "PETマークのついた飲料ボトル",
    collectionNote: "Remove cap and label, rinse, and crush",
    collectionNoteJa: "キャップとラベルを外し、すすいでつぶす",
  },
  cans: {
    id: "cans",
    name: "Cans / Metals",
    nameJa: "缶・金属類",
    color: "#f59e0b",
    description: "Aluminum and steel cans, metal lids",
    descriptionJa: "アルミ缶・スチール缶・金属類",
    collectionNote: "Rinse clean",
    collectionNoteJa: "軽くすすいでください",
  },
  glass: {
    id: "glass",
    name: "Glass",
    nameJa: "ガラス類",
    color: "#3b82f6",
    description: "Glass bottles and containers",
    descriptionJa: "ガラス瓶・ガラス容器",
    collectionNote: "Separate by color: clear, brown, other",
    collectionNoteJa: "無色・茶色・その他に分けて",
  },
  paper: {
    id: "paper",
    name: "Paper / Cardboard",
    nameJa: "紙類・段ボール",
    color: "#84cc16",
    description: "Newspapers, magazines, cardboard, paper boxes",
    descriptionJa: "新聞・雑誌・段ボール・紙箱",
    collectionNote: "Tie in bundles. Flatten cardboard",
    collectionNoteJa: "紐で縛ってください。段ボールは折りたたむ",
  },
  oversized: {
    id: "oversized",
    name: "Oversized Waste",
    nameJa: "粗大ゴミ",
    color: "#f97316",
    description: "Large items that don't fit in regular bags",
    descriptionJa: "通常の袋に入らない大型ゴミ",
    collectionNote: "Advance booking required. Fee applies.",
    collectionNoteJa: "事前予約が必要。費用がかかります。",
  },
  hazardous: {
    id: "hazardous",
    name: "Hazardous / Special Disposal",
    nameJa: "危険・特別ゴミ",
    color: "#dc2626",
    description: "Batteries, chemicals, spray cans, fluorescent tubes",
    descriptionJa: "電池・化学物質・スプレー缶・蛍光灯",
    collectionNote: "Special collection points. Do not mix with regular waste.",
    collectionNoteJa: "専用回収場所へ。通常ゴミに混ぜないこと。",
  },
};

const UNIVERSAL_ITEMS: ItemRule[] = [
  {
    itemName: "PET bottle",
    itemNameJa: "ペットボトル",
    categoryId: "petBottle",
    synonyms: ["plastic bottle", "water bottle", "soda bottle", "pet bottle", "beverage bottle", "drink bottle", "cola bottle", "juice bottle"],
    synonymsJa: ["ペット", "ペットボトル", "プラスチックボトル", "水のボトル", "飲料ボトル"],
    preparationSteps: [
      "Remove the cap (recycle separately as plastic)",
      "Remove the label (recycle as plastic)",
      "Rinse the inside thoroughly",
      "Crush flat to save space",
    ],
    preparationStepsJa: [
      "キャップを外す（プラスチックとして別途リサイクル）",
      "ラベルを剥がす（プラスチックとしてリサイクル）",
      "内側をよくすすぐ",
      "つぶして平らにする",
    ],
    specialNotes: ["PET bottles must have the PET mark (PETマーク)"],
    specialNotesJa: ["PETマークのついたもののみ"],
    tags: ["beverage", "drink", "container", "recyclable"],
  },
  {
    itemName: "Aluminum can",
    itemNameJa: "アルミ缶",
    categoryId: "cans",
    synonyms: ["beer can", "soda can", "aluminum can", "aluminium can", "drink can", "tin can", "cola can", "juice can", "coffee can"],
    synonymsJa: ["缶", "アルミ缶", "ビール缶", "ジュース缶", "コーヒー缶", "飲料缶"],
    preparationSteps: [
      "Rinse thoroughly to remove liquid",
      "Do not crush (some municipalities require intact cans)",
    ],
    preparationStepsJa: [
      "液体をよくすすいで出す",
      "つぶさないで出す（自治体によって異なる）",
    ],
    specialNotes: [],
    specialNotesJa: [],
    tags: ["beverage", "drink", "metal", "recyclable"],
  },
  {
    itemName: "Steel can",
    itemNameJa: "スチール缶",
    categoryId: "cans",
    synonyms: ["steel can", "tin can", "food can", "canned food", "canned goods", "metal can"],
    synonymsJa: ["スチール缶", "食缶", "缶詰"],
    preparationSteps: [
      "Empty contents completely",
      "Rinse thoroughly",
    ],
    preparationStepsJa: [
      "中身を完全に出す",
      "よくすすぐ",
    ],
    specialNotes: [],
    specialNotesJa: [],
    tags: ["food", "metal", "recyclable"],
  },
  {
    itemName: "Glass bottle",
    itemNameJa: "ガラス瓶",
    categoryId: "glass",
    synonyms: ["glass bottle", "wine bottle", "beer bottle", "sake bottle", "sauce bottle", "glass jar", "glass container", "bottle"],
    synonymsJa: ["ガラス瓶", "瓶", "ワイン瓶", "ビール瓶", "日本酒瓶", "ガラス容器"],
    preparationSteps: [
      "Empty completely",
      "Rinse thoroughly",
      "Separate by color: clear, brown, or other colors",
    ],
    preparationStepsJa: [
      "中身を完全に出す",
      "よくすすぐ",
      "色別に分ける：無色、茶色、その他",
    ],
    specialNotes: ["Some municipalities do not accept broken glass in regular glass recycling"],
    specialNotesJa: ["割れたガラスは通常のガラスリサイクルとは別に扱われる場合があります"],
    tags: ["glass", "beverage", "food", "recyclable"],
  },
  {
    itemName: "Newspaper",
    itemNameJa: "新聞紙",
    categoryId: "paper",
    synonyms: ["newspaper", "news paper", "daily paper", "newsprint"],
    synonymsJa: ["新聞", "新聞紙"],
    preparationSteps: [
      "Tie in bundles with string",
      "Keep dry — wet paper is not accepted",
    ],
    preparationStepsJa: [
      "紐で束ねる",
      "濡れた新聞は受け付けられません",
    ],
    specialNotes: [],
    specialNotesJa: [],
    tags: ["paper", "recyclable"],
  },
  {
    itemName: "Cardboard",
    itemNameJa: "段ボール",
    categoryId: "paper",
    synonyms: ["cardboard", "cardboard box", "box", "corrugated cardboard", "packing box", "shipping box", "moving box"],
    synonymsJa: ["段ボール", "ダンボール", "段ボール箱", "箱"],
    preparationSteps: [
      "Flatten and fold down to a manageable size",
      "Remove tape and staples if possible",
      "Tie in bundles with string",
      "Keep dry",
    ],
    preparationStepsJa: [
      "平らに折りたたむ",
      "テープやホッチキスはできれば外す",
      "紐で束ねる",
      "濡れないようにする",
    ],
    specialNotes: [],
    specialNotesJa: [],
    tags: ["paper", "recyclable", "packaging"],
  },
  {
    itemName: "Magazine",
    itemNameJa: "雑誌",
    categoryId: "paper",
    synonyms: ["magazine", "booklet", "catalog", "catalogue", "brochure", "flyer", "leaflet", "pamphlet", "book"],
    synonymsJa: ["雑誌", "本", "冊子", "カタログ", "パンフレット"],
    preparationSteps: [
      "Tie in bundles with string",
    ],
    preparationStepsJa: [
      "紐で束ねる",
    ],
    specialNotes: [],
    specialNotesJa: [],
    tags: ["paper", "recyclable"],
  },
  {
    itemName: "Battery",
    itemNameJa: "電池",
    categoryId: "hazardous",
    synonyms: ["battery", "batteries", "aa battery", "aaa battery", "d battery", "c battery", "9v battery", "alkaline battery", "rechargeable battery", "button battery", "coin battery", "lithium battery"],
    synonymsJa: ["電池", "乾電池", "充電池", "ボタン電池", "リチウム電池"],
    preparationSteps: [
      "Tape the terminals to prevent short circuits",
      "Take to designated battery collection points at stores or community centers",
    ],
    preparationStepsJa: [
      "端子にテープを貼って短絡を防ぐ",
      "店舗や公民館の電池回収ボックスに持参",
    ],
    specialNotes: ["Do NOT put batteries in regular garbage — fire hazard"],
    specialNotesJa: ["電池を通常ゴミに入れないこと — 発火の危険があります"],
    tags: ["electronics", "hazardous", "fire-hazard"],
  },
  {
    itemName: "Spray can",
    itemNameJa: "スプレー缶",
    categoryId: "hazardous",
    synonyms: ["spray can", "aerosol", "aerosol can", "deodorant can", "hair spray", "paint spray", "insecticide spray", "spray bottle", "pressurized can"],
    synonymsJa: ["スプレー缶", "エアゾール缶", "殺虫剤缶", "ヘアスプレー缶"],
    preparationSteps: [
      "Use up all contents completely",
      "Puncture the can in a well-ventilated area outdoors",
      "Let it air out fully before disposal",
    ],
    preparationStepsJa: [
      "中身を完全に使い切る",
      "屋外の風通しの良い場所で穴を開ける",
      "十分に空気を抜いてから出す",
    ],
    specialNotes: ["NEVER puncture near fire or flame", "Some municipalities have special spray can collection days"],
    specialNotesJa: ["絶対に火の近くで穴を開けないこと", "スプレー缶専用回収日がある自治体もあります"],
    tags: ["hazardous", "fire-hazard", "pressurized"],
  },
  {
    itemName: "Fluorescent light",
    itemNameJa: "蛍光灯",
    categoryId: "hazardous",
    synonyms: ["fluorescent bulb", "fluorescent tube", "fluorescent light", "cfl bulb", "compact fluorescent", "tube light", "neon light"],
    synonymsJa: ["蛍光灯", "蛍光管", "蛍光球"],
    preparationSteps: [
      "Wrap in original packaging or newspaper to prevent breakage",
      "Take to designated hazardous waste collection points",
    ],
    preparationStepsJa: [
      "元の包装か新聞紙で包んで破損を防ぐ",
      "指定の有害ゴミ回収場所に持参",
    ],
    specialNotes: ["Contains mercury — handle with care"],
    specialNotesJa: ["水銀を含む — 取り扱いに注意"],
    tags: ["hazardous", "mercury", "lighting"],
  },
  {
    itemName: "Plastic packaging",
    itemNameJa: "プラスチック包装",
    categoryId: "plastic",
    synonyms: ["plastic bag", "plastic wrap", "plastic packaging", "pla packaging", "bubble wrap", "styrofoam tray", "foam tray", "plastic tray", "plastic container", "plastic cup", "plastic lid", "plastic film"],
    synonymsJa: ["プラスチック袋", "プラ袋", "プラ容器", "プラパッケージ", "発泡スチロール", "トレー"],
    preparationSteps: [
      "Check for the プラ (PLA) recycling mark",
      "Rinse and remove food residue",
      "Do not wash with soap — just rinse",
    ],
    preparationStepsJa: [
      "プラマークを確認する",
      "食べ残しをすすいで落とす",
      "洗剤は使わず、すすぐだけでよい",
    ],
    specialNotes: ["Items heavily soiled or with strong odors go to burnable waste"],
    specialNotesJa: ["汚れがひどいものや臭いが強いものは燃えるゴミへ"],
    tags: ["plastic", "packaging", "recyclable"],
  },
  {
    itemName: "Old clothes",
    itemNameJa: "古着",
    categoryId: "burnable",
    synonyms: ["old clothes", "clothing", "shirt", "pants", "jeans", "dress", "jacket", "coat", "sweater", "underwear", "socks", "shoes", "sneakers", "boots", "fabric", "textile"],
    synonymsJa: ["古着", "衣類", "洋服", "Tシャツ", "ズボン", "ジーンズ", "ジャケット", "コート", "靴", "靴下"],
    preparationSteps: [
      "Donate to charity or clothing drives if in good condition",
      "If worn out, dispose as burnable waste",
    ],
    preparationStepsJa: [
      "状態が良ければ寄付や古着回収へ",
      "使い古したものは燃えるゴミへ",
    ],
    specialNotes: ["Some municipalities have textile recycling collections"],
    specialNotesJa: ["衣類回収を実施している自治体もあります"],
    tags: ["textile", "clothing"],
  },
  {
    itemName: "Food waste",
    itemNameJa: "生ゴミ",
    categoryId: "burnable",
    synonyms: ["food waste", "food scraps", "kitchen waste", "leftovers", "vegetable scraps", "fruit peel", "fish bones", "meat scraps", "eggshell", "tea leaves", "coffee grounds"],
    synonymsJa: ["生ゴミ", "食べ残し", "野菜くず", "果物の皮", "魚の骨", "卵の殻", "茶葉", "コーヒーかす"],
    preparationSteps: [
      "Drain water thoroughly before disposal",
      "Seal in a bag to prevent odors",
    ],
    preparationStepsJa: [
      "よく水を切ってから出す",
      "臭い漏れを防ぐため袋に密封する",
    ],
    specialNotes: [],
    specialNotesJa: [],
    tags: ["food", "organic"],
  },
  {
    itemName: "Ceramic cup",
    itemNameJa: "陶器のカップ",
    categoryId: "nonBurnable",
    synonyms: ["ceramic cup", "ceramic mug", "mug", "cup", "bowl", "plate", "dish", "ceramic bowl", "ceramic plate", "pottery", "earthenware", "porcelain"],
    synonymsJa: ["陶器", "カップ", "茶碗", "皿", "ボウル", "マグカップ", "陶磁器"],
    preparationSteps: [
      "Wrap in newspaper if broken to prevent injuries",
    ],
    preparationStepsJa: [
      "割れている場合は怪我防止のため新聞紙で包む",
    ],
    specialNotes: ["Ceramic and porcelain items are usually non-burnable"],
    specialNotesJa: ["陶磁器類は通常、燃えないゴミです"],
    tags: ["ceramic", "kitchenware"],
  },
  {
    itemName: "Smartphone",
    itemNameJa: "スマートフォン",
    categoryId: "hazardous",
    synonyms: ["smartphone", "phone", "mobile phone", "cell phone", "iphone", "android phone", "mobile", "cellphone"],
    synonymsJa: ["スマートフォン", "スマホ", "携帯電話", "携帯", "iPhone", "アンドロイド"],
    preparationSteps: [
      "Delete all personal data before disposal",
      "Take to electronics recycling points at electronics stores (Bic Camera, Yodobashi, etc.)",
      "Or take to a carrier store",
    ],
    preparationStepsJa: [
      "廃棄前に個人データを全て削除する",
      "家電量販店（ビックカメラ、ヨドバシなど）の回収ボックスへ",
      "またはキャリアショップへ",
    ],
    specialNotes: ["Contains lithium battery — do NOT put in regular garbage"],
    specialNotesJa: ["リチウム電池を含む — 通常ゴミに入れないこと"],
    tags: ["electronics", "hazardous", "lithium-battery"],
  },
  {
    itemName: "Laptop computer",
    itemNameJa: "ノートパソコン",
    categoryId: "hazardous",
    synonyms: ["laptop", "notebook computer", "pc", "macbook", "computer", "notebook"],
    synonymsJa: ["ノートパソコン", "ノートPC", "パソコン", "PC", "マックブック", "コンピュータ"],
    preparationSteps: [
      "Delete all personal data before disposal",
      "Use PC 3R (Recycling, Reuse, Reduce) system — call 03-5282-7685 or visit www.pc3r.jp",
      "Manufacturer take-back programs are available",
    ],
    preparationStepsJa: [
      "廃棄前に個人データを全て削除する",
      "パソコン3R推進協会へ — 03-5282-7685またはwww.pc3r.jp",
      "メーカーの回収プログラムも利用可能",
    ],
    specialNotes: ["PCs are covered by the PC Recycling Law (パソコンリサイクル法)"],
    specialNotesJa: ["パソコンはパソコンリサイクル法の対象です"],
    tags: ["electronics", "hazardous", "recyclable"],
  },
  {
    itemName: "Umbrella",
    itemNameJa: "傘",
    categoryId: "nonBurnable",
    synonyms: ["umbrella", "rain umbrella", "folding umbrella", "parasol"],
    synonymsJa: ["傘", "雨傘", "折りたたみ傘", "日傘"],
    preparationSteps: [
      "Disassemble if possible — separate metal frame from fabric",
    ],
    preparationStepsJa: [
      "できれば分解して金属フレームと布に分ける",
    ],
    specialNotes: ["Large umbrellas may require oversized waste booking"],
    specialNotesJa: ["大きな傘は粗大ゴミの予約が必要な場合があります"],
    tags: ["metal", "fabric"],
  },
  {
    itemName: "Broken glass",
    itemNameJa: "割れたガラス",
    categoryId: "nonBurnable",
    synonyms: ["broken glass", "glass shard", "broken mirror", "broken bottle", "glass fragment"],
    synonymsJa: ["割れたガラス", "ガラスの破片", "割れた鏡", "割れた瓶"],
    preparationSteps: [
      "Wrap in several layers of newspaper or thick paper",
      "Label clearly as 'Broken glass — Dangerous' (ガラス破片・危険)",
    ],
    preparationStepsJa: [
      "新聞紙など厚い紙で何重にも包む",
      "「ガラス破片・危険」と明記する",
    ],
    specialNotes: ["Always wrap broken glass to prevent injury to collectors"],
    specialNotesJa: ["収集作業員の怪我を防ぐために必ず包む"],
    tags: ["glass", "sharp", "dangerous"],
  },
  {
    itemName: "Sofa",
    itemNameJa: "ソファ",
    categoryId: "oversized",
    synonyms: ["sofa", "couch", "loveseat", "sectional sofa", "futon sofa"],
    synonymsJa: ["ソファ", "ソファー", "カウチ", "長椅子"],
    preparationSteps: [
      "Contact your municipality to schedule oversized waste collection",
      "Purchase a sticker/ticket (粗大ゴミ処理券) at convenience stores",
      "Attach the sticker and place item at the designated collection point",
    ],
    preparationStepsJa: [
      "自治体に粗大ゴミ回収の予約を入れる",
      "コンビニなどで粗大ゴミ処理券を購入",
      "シールを貼り、指定の場所に出す",
    ],
    specialNotes: ["Fee varies by municipality and item size"],
    specialNotesJa: ["費用は自治体や品目によって異なります"],
    tags: ["furniture", "oversized"],
  },
  {
    itemName: "Bicycle",
    itemNameJa: "自転車",
    categoryId: "oversized",
    synonyms: ["bicycle", "bike", "road bike", "mountain bike", "electric bike", "e-bike", "cycle"],
    synonymsJa: ["自転車", "チャリ", "ロードバイク", "マウンテンバイク", "電動自転車"],
    preparationSteps: [
      "Contact your municipality to schedule oversized waste collection",
      "Purchase an oversized waste sticker from a convenience store",
    ],
    preparationStepsJa: [
      "自治体に粗大ゴミ回収の予約を入れる",
      "コンビニなどで粗大ゴミ処理券を購入",
    ],
    specialNotes: ["Electric bikes contain lithium batteries — declare this when booking"],
    specialNotesJa: ["電動自転車はリチウム電池含む — 予約時に申告する"],
    tags: ["oversized", "vehicle"],
  },
  {
    itemName: "Lighter",
    itemNameJa: "ライター",
    categoryId: "hazardous",
    synonyms: ["lighter", "cigarette lighter", "gas lighter", "disposable lighter"],
    synonymsJa: ["ライター", "使い捨てライター", "ガスライター"],
    preparationSteps: [
      "Use up all remaining gas completely",
      "Operate the ignition outside until no gas remains",
    ],
    preparationStepsJa: [
      "残っているガスを完全に使い切る",
      "屋外でガスがなくなるまで点火操作をする",
    ],
    specialNotes: ["Do not put in regular garbage — explosion hazard"],
    specialNotesJa: ["通常ゴミに入れないこと — 爆発の危険があります"],
    tags: ["hazardous", "fire-hazard", "gas"],
  },
  {
    itemName: "TV",
    itemNameJa: "テレビ",
    categoryId: "hazardous",
    synonyms: ["television", "tv", "flat screen tv", "lcd tv", "plasma tv", "monitor"],
    synonymsJa: ["テレビ", "液晶テレビ", "モニター", "ディスプレイ"],
    preparationSteps: [
      "Contact manufacturer or retailer for recycling (Home Appliance Recycling Law)",
      "Pay a recycling fee (リサイクル料金)",
      "Large electronics retailers can arrange collection",
    ],
    preparationStepsJa: [
      "メーカーか販売店に連絡（家電リサイクル法）",
      "リサイクル料金を支払う",
      "大型家電量販店で引き取り手配も可",
    ],
    specialNotes: ["TVs are covered by the Home Appliance Recycling Law (家電リサイクル法). NOT accepted in regular garbage."],
    specialNotesJa: ["テレビは家電リサイクル法の対象。通常ゴミでは出せません。"],
    tags: ["electronics", "hazardous", "large-appliance"],
  },
  {
    itemName: "Refrigerator",
    itemNameJa: "冷蔵庫",
    categoryId: "hazardous",
    synonyms: ["refrigerator", "fridge", "freezer", "mini fridge"],
    synonymsJa: ["冷蔵庫", "冷凍庫", "フリーザー", "冷蔵庫"],
    preparationSteps: [
      "Empty all contents",
      "Contact manufacturer or retailer for recycling (Home Appliance Recycling Law)",
      "Pay a recycling fee",
    ],
    preparationStepsJa: [
      "中身を全て出す",
      "メーカーか販売店に連絡（家電リサイクル法）",
      "リサイクル料金を支払う",
    ],
    specialNotes: ["Covered by the Home Appliance Recycling Law (家電リサイクル法)"],
    specialNotesJa: ["家電リサイクル法の対象品目"],
    tags: ["electronics", "hazardous", "large-appliance"],
  },
  {
    itemName: "Washing machine",
    itemNameJa: "洗濯機",
    categoryId: "hazardous",
    synonyms: ["washing machine", "washer", "laundry machine", "clothes washer", "dryer"],
    synonymsJa: ["洗濯機", "洗濯乾燥機", "乾燥機"],
    preparationSteps: [
      "Contact manufacturer or retailer for recycling (Home Appliance Recycling Law)",
      "Pay a recycling fee",
    ],
    preparationStepsJa: [
      "メーカーか販売店に連絡（家電リサイクル法）",
      "リサイクル料金を支払う",
    ],
    specialNotes: ["Covered by the Home Appliance Recycling Law (家電リサイクル法)"],
    specialNotesJa: ["家電リサイクル法の対象品目"],
    tags: ["electronics", "hazardous", "large-appliance"],
  },
  {
    itemName: "Rubber gloves",
    itemNameJa: "ゴム手袋",
    categoryId: "burnable",
    synonyms: ["rubber gloves", "latex gloves", "cleaning gloves", "dish gloves", "rubber band"],
    synonymsJa: ["ゴム手袋", "ラテックス手袋", "ゴムバンド", "輪ゴム"],
    preparationSteps: [],
    preparationStepsJa: [],
    specialNotes: [],
    specialNotesJa: [],
    tags: ["rubber", "kitchen"],
  },
  {
    itemName: "Cooking oil",
    itemNameJa: "食用油",
    categoryId: "burnable",
    synonyms: ["cooking oil", "vegetable oil", "olive oil", "used oil", "frying oil", "salad oil"],
    synonymsJa: ["食用油", "サラダ油", "オリーブオイル", "揚げ油", "廃油"],
    preparationSteps: [
      "Let cool completely",
      "Pour into a bag with absorbent material (newspaper or cloth) and seal",
      "Some municipalities have special oil collection programs",
    ],
    preparationStepsJa: [
      "完全に冷ましてから",
      "新聞紙や布などに染み込ませて袋に入れて密封",
      "廃食用油回収を実施している自治体もあります",
    ],
    specialNotes: ["Do not pour down the drain — causes water pollution"],
    specialNotesJa: ["排水溝に流さないこと — 水質汚染の原因になります"],
    tags: ["food", "liquid", "hazardous-if-poured"],
  },
  {
    itemName: "Medicine",
    itemNameJa: "薬",
    categoryId: "burnable",
    synonyms: ["medicine", "medication", "pills", "tablets", "capsules", "prescription drugs", "over the counter medicine", "vitamins"],
    synonymsJa: ["薬", "医薬品", "錠剤", "カプセル", "処方薬", "市販薬", "ビタミン"],
    preparationSteps: [
      "Remove from bottles and return bottles separately",
      "Dispose of pills/tablets as burnable waste",
      "Some pharmacies accept returned unused medicine",
    ],
    preparationStepsJa: [
      "瓶から出して瓶は別に捨てる",
      "錠剤・カプセルは燃えるゴミへ",
      "一部の薬局では未使用薬を回収しています",
    ],
    specialNotes: [],
    specialNotesJa: [],
    tags: ["pharmaceutical", "health"],
  },
];

export const MUNICIPALITIES: MunicipalityProfile[] = [
  {
    id: "tokyo-shibuya",
    name: "Shibuya, Tokyo",
    nameJa: "東京都渋谷区",
    prefecture: "Tokyo",
    prefectureJa: "東京都",
    collectionDays: {
      burnable: "Tuesday, Friday",
      nonBurnable: "2nd and 4th Saturday",
      plastic: "Monday, Thursday",
      petBottle: "Monday, Thursday",
      cans: "Wednesday",
      glass: "Wednesday",
      paper: "Wednesday",
    },
    website: "https://www.city.shibuya.tokyo.jp/kurashi/gomi/",
    hotline: "03-3463-1211",
    fallbackGuidance: "When in doubt, contact Shibuya Ward at 03-3463-1211 or visit the ward office.",
    fallbackGuidanceJa: "不明な場合は渋谷区（03-3463-1211）または区役所にお問い合わせください。",
    categories: [
      COMMON_CATEGORIES.burnable,
      COMMON_CATEGORIES.nonBurnable,
      COMMON_CATEGORIES.plastic,
      COMMON_CATEGORIES.petBottle,
      COMMON_CATEGORIES.cans,
      COMMON_CATEGORIES.glass,
      COMMON_CATEGORIES.paper,
      COMMON_CATEGORIES.oversized,
      COMMON_CATEGORIES.hazardous,
    ],
    items: UNIVERSAL_ITEMS,
  },
  {
    id: "osaka-city",
    name: "Osaka City",
    nameJa: "大阪市",
    prefecture: "Osaka",
    prefectureJa: "大阪府",
    collectionDays: {
      burnable: "Monday, Thursday",
      nonBurnable: "1st and 3rd Wednesday",
      plastic: "Tuesday",
      petBottle: "Tuesday",
      cans: "2nd and 4th Wednesday",
      glass: "2nd and 4th Wednesday",
      paper: "2nd and 4th Wednesday",
    },
    website: "https://www.city.osaka.lg.jp/kankyo/category/3706-0-0-0-0-0-0-0-0-0.html",
    hotline: "06-6630-3347",
    fallbackGuidance: "When in doubt, contact Osaka City at 06-6630-3347 or visit city.osaka.lg.jp",
    fallbackGuidanceJa: "不明な場合は大阪市（06-6630-3347）またはcity.osaka.lg.jpにお問い合わせください。",
    categories: [
      COMMON_CATEGORIES.burnable,
      COMMON_CATEGORIES.nonBurnable,
      COMMON_CATEGORIES.plastic,
      COMMON_CATEGORIES.petBottle,
      COMMON_CATEGORIES.cans,
      COMMON_CATEGORIES.glass,
      COMMON_CATEGORIES.paper,
      COMMON_CATEGORIES.oversized,
      COMMON_CATEGORIES.hazardous,
    ],
    items: [
      ...UNIVERSAL_ITEMS,
      // Osaka-specific: ceramic cups are burnable (different from Tokyo)
      {
        itemName: "Ceramic cup (Osaka rule)",
        itemNameJa: "陶器のカップ（大阪ルール）",
        categoryId: "burnable",
        synonyms: ["ceramic cup osaka", "pottery osaka"],
        synonymsJa: [],
        preparationSteps: [],
        preparationStepsJa: [],
        specialNotes: ["In Osaka, small ceramic items (under 30cm) are burnable"],
        specialNotesJa: ["大阪では30cm以下の小さな陶磁器は燃えるゴミです"],
        tags: ["ceramic", "kitchenware", "osaka-specific"],
      },
    ],
  },
  {
    id: "kyoto-city",
    name: "Kyoto City",
    nameJa: "京都市",
    prefecture: "Kyoto",
    prefectureJa: "京都府",
    collectionDays: {
      burnable: "Tuesday, Friday",
      nonBurnable: "1st and 3rd Monday",
      plastic: "Wednesday",
      petBottle: "Wednesday",
      cans: "2nd and 4th Monday",
      glass: "2nd and 4th Monday",
      paper: "Every Saturday (neighborhood collection)",
    },
    website: "https://www.city.kyoto.lg.jp/kankyo/page/0000025016.html",
    hotline: "075-213-4930",
    fallbackGuidance: "When in doubt, contact Kyoto City at 075-213-4930 or visit the website.",
    fallbackGuidanceJa: "不明な場合は京都市（075-213-4930）にお問い合わせください。",
    categories: [
      COMMON_CATEGORIES.burnable,
      COMMON_CATEGORIES.nonBurnable,
      COMMON_CATEGORIES.plastic,
      COMMON_CATEGORIES.petBottle,
      COMMON_CATEGORIES.cans,
      COMMON_CATEGORIES.glass,
      COMMON_CATEGORIES.paper,
      COMMON_CATEGORIES.oversized,
      COMMON_CATEGORIES.hazardous,
    ],
    items: UNIVERSAL_ITEMS,
  },
  {
    id: "yokohama-city",
    name: "Yokohama City",
    nameJa: "横浜市",
    prefecture: "Kanagawa",
    prefectureJa: "神奈川県",
    collectionDays: {
      burnable: "Monday, Thursday",
      nonBurnable: "Wednesday (2x/month)",
      plastic: "Friday",
      petBottle: "Friday",
      cans: "Wednesday",
      glass: "Wednesday",
      paper: "Wednesday",
    },
    website: "https://www.city.yokohama.lg.jp/kurashi/machizukuri-kankyo/gomi-recycle/",
    hotline: "045-671-3816",
    fallbackGuidance: "When in doubt, contact Yokohama City at 045-671-3816.",
    fallbackGuidanceJa: "不明な場合は横浜市（045-671-3816）にお問い合わせください。",
    categories: [
      COMMON_CATEGORIES.burnable,
      COMMON_CATEGORIES.nonBurnable,
      COMMON_CATEGORIES.plastic,
      COMMON_CATEGORIES.petBottle,
      COMMON_CATEGORIES.cans,
      COMMON_CATEGORIES.glass,
      COMMON_CATEGORIES.paper,
      COMMON_CATEGORIES.oversized,
      COMMON_CATEGORIES.hazardous,
    ],
    items: UNIVERSAL_ITEMS,
  },
  {
    id: "fukuoka-city",
    name: "Fukuoka City",
    nameJa: "福岡市",
    prefecture: "Fukuoka",
    prefectureJa: "福岡県",
    collectionDays: {
      burnable: "Monday, Thursday",
      nonBurnable: "1st and 3rd Tuesday",
      plastic: "Wednesday",
      petBottle: "Wednesday",
      cans: "2nd and 4th Tuesday",
      glass: "2nd and 4th Tuesday",
      paper: "2nd and 4th Saturday",
    },
    website: "https://www.city.fukuoka.lg.jp/kankyo/3r/life/gomi/",
    hotline: "092-711-4346",
    fallbackGuidance: "When in doubt, contact Fukuoka City at 092-711-4346.",
    fallbackGuidanceJa: "不明な場合は福岡市（092-711-4346）にお問い合わせください。",
    categories: [
      COMMON_CATEGORIES.burnable,
      COMMON_CATEGORIES.nonBurnable,
      COMMON_CATEGORIES.plastic,
      COMMON_CATEGORIES.petBottle,
      COMMON_CATEGORIES.cans,
      COMMON_CATEGORIES.glass,
      COMMON_CATEGORIES.paper,
      COMMON_CATEGORIES.oversized,
      COMMON_CATEGORIES.hazardous,
    ],
    items: UNIVERSAL_ITEMS,
  },
];

export function getMunicipalityById(id: string): MunicipalityProfile | undefined {
  return MUNICIPALITIES.find((m) => m.id === id);
}
